// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLocalIPPrefix():Promise<string>;

export function SendWOL(arg1:string):Promise<void>;

export function StartScan(arg1:main.ScanRequest):Promise<void>;

export function StopScan():Promise<void>;
