// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIPPrefix() {
  return window['go']['main']['App']['GetLocalIPPrefix']();
}

export function GetMACAddress(arg1) {
  return window['go']['main']['App']['GetMACAddress'](arg1);
}

export function SendWOL(arg1) {
  return window['go']['main']['App']['SendWOL'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
